Change to TransactedTest which prevents the intermittent error junit.framework.ComparisonFailure: expected:<B> but was:<C> (or similar) from occurring on either the commit or rollback portion of the test. The error occurs when the test consumer testConsumer1 bind frames arrive at the server before the message bodies with A,B,C and cause queue 1 to start a round-robin distribution for these messages when they finally do arrive.